### ISSUE TITLE
Parsing birth date could be wrong if the current user calendar setting is Buddhist.

### ISSUE THREAD

**Issue by rathapolk** [Mattijah/QKMRZParser#2] opened 2020-11-11 12:15 UTC
Parsing birth date could be wrong if the current user calendar setting is Buddhist. 
Note, Buddhist year is 543 years ahead of AD (year 2020 is equal to 2563 in buddhist year). 

To reproduce...
1. Open Settings
2. Go to General > Language & Region
3. Set Calendar to Buddhist.

To fix this issue, change the current calendar to a fixed Gregorian year.
So that the code ...

//  MRZFieldFormatter.swift
```
private func birthdate(from string: String) -> Date? {
        guard CharacterSet.decimalDigits.isSuperset(of: CharacterSet(charactersIn: string)) else {
            return nil
        }
        
        let currentYear = Calendar.current.component(.year, from: Date()) - 2000
        let parsedYear = Int(string.substring(0, to: 1))!
        let centennial = (parsedYear > currentYear) ? "19" : "20"
        
        return dateFormatter.date(from: centennial + string)
    }
```

The line...
```
let currentYear = Calendar.current.component(.year, from: Date()) - 2000
```
Should be changed to ...
```
let currentYear = Calendar(identifier: .gregorian).component(.year, from: Date()) - 2000
```

**Comment by Mattijah** [comment] 2020-11-11 12:22
Thank you @rathapolk! I will look at it over the weekend as I have some other changes and improvements I'd like to address too.

**Comment by Mattijah** [comment] 2022-04-02 20:27
Took a while, but the issue is now resolved in v2. Thanks again!

**Closed as completed by Mattijah** 2022-04-02 20:27 UTC
